substitutions:
  name: !secret device_1_name
  friendly_name: !secret device_1_friendly_name
  static_ip: !secret device_1_ip
  api_encryption_key: !secret device_1_api_key
  manifest_path: !secret device_1_manifest_path
  gateway: !secret gateway
  subnet: !secret subnet

packages:
  base: !include common/ble-proxy-base.yaml
