packages:
  esphome.bluetooth-proxy:
    github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: homeassilol.ble-proxies
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble:
  max_connections: 3

api:
  encryption:
    key: ${api_encryption_key}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  manual_ip:
    static_ip: ${static_ip}
    gateway: ${gateway}
    subnet: ${subnet}

esp32_ble_tracker:
  scan_parameters:
    interval: 460ms
    window: 120ms
    active: true
    continuous: true

bluetooth_proxy:
  active: true
  connection_slots: 3

ota:
  - platform: esphome
  - platform: http_request

http_request:

update:
  - platform: http_request
    name: "${friendly_name} Firmware"
    source: https://homeassilol.github.io/esphome-firmware/${manifest_path}/manifest.json

button:
  - platform: safe_mode
    name: "${friendly_name} Safe Mode"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: template
    name: "${friendly_name} Free Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    unit_of_measurement: 'B'
    update_interval: 60s
